

gamegrad 1
#
#

gamesimple 1
#
#

attentiveness 80
# 0 - 100 насколько внимателен противник (обычный), замечает и разворачивается к танку игрока
# 100 - не видит, 0 - замечает всегда

h_attentiveness 50
# 0 - 100 насколько внимателен охотник(hunter), замечает и разворачивается к танку игрока
# 100 - не видит, 0 - замечает всегда

reaction 60
# скорость реакции при стрельбе обычного противника при появлении игрока на линии огня
# 100 - не стреляет, 0 - стреляет как только увидит

h_reaction 5
# скорость реакции при стрельбе охотника(hunter) при появлении игрока на линии огня
# 100 - не стреляет, 0 - стреляет как только увидит

crash 70
# внимательность к помеченным стенам
# 100 - специально не разворачивается к ним, 0 - разворачивается обязательно к ближайшей стене

c_crash 10
# внимательность к помеченным стенам, танков-AI-разрушителей
# 100 - специально не разворачивается к ним, 0 - разворачивается обязательно к ближайшей стене

score_l1 200
score_l2 500
score_l3 1000
#
#

time_rf_player 28
time_rf_easy 42
time_rf_normal 48
time_rf_hard 54
time_rf_boss1 48
time_rf_boss2 48
time_rf_boss3 48
# время перезарядки в (1/32 sec)
# интервал [12, 1000] 

speed_player 12
speed_easy 12
speed_normal 14
speed_hard 18
speed_nuc 28
speed_boss1 14
speed_boss2 16
speed_boss3 14
# скорость перемещения
#

live_player 1
live_easy 1
live_normal 1
live_hard 2
live_nuc 2
live_boss1 10
live_boss2 10
live_boss3 5
# количество жизней
#


bullet1_speed 1.5
bullet2_speed 2.2
bullet3_speed 1.4
# скорость пули
#

