OrderURL	"http://www.enkord.com/games/armadatanks/order/?from="

MusicGame	"BaseT\\Music\\game.it"
MusicMenu	"BaseT\\Music\\menu.it"

GameVer 	"Ver. 2.0.4"

DiffMod LiveT	0 500 
DiffMod LiveT	1 300 
DiffMod LiveT	2 200 

DiffMod LiveF	0 100 
DiffMod LiveF	1 200 
DiffMod LiveF	2 300 

DiffMod Money	0 150 
DiffMod Money	1 200 
DiffMod Money	2 300

Attentiveness	80
# 0 - 100 ­ бЄ®«мЄ® ў­Ё¬ вҐ«Ґ­ Їа®вЁў­ЁЄ (®Ўлз­л©), § ¬Ґз Ґв Ё а §ў®а зЁў Ґвбп Є в ­Єг ЁЈа®Є 
# 100 - ­Ґ ўЁ¤Ёв, 0 - § ¬Ґз Ґв ўбҐЈ¤ 

AttentivenessH	50
# 0 - 100 ­ бЄ®«мЄ® ў­Ё¬ вҐ«Ґ­ ®е®в­ЁЄ(hunter), § ¬Ґз Ґв Ё а §ў®а зЁў Ґвбп Є в ­Єг ЁЈа®Є 
# 100 - ­Ґ ўЁ¤Ёв, 0 - § ¬Ґз Ґв ўбҐЈ¤ 

Reaction	60
# бЄ®а®бвм аҐ ЄжЁЁ ЇаЁ бваҐ«мЎҐ ®Ўлз­®Ј® Їа®вЁў­ЁЄ  ЇаЁ Ї®пў«Ґ­ЁЁ ЁЈа®Є  ­  «Ё­ЁЁ ®Ј­п
# 100 - ­Ґ бваҐ«пҐв, 0 - бваҐ«пҐв Є Є в®«мЄ® гўЁ¤Ёв

ReactionH	5
# бЄ®а®бвм аҐ ЄжЁЁ ЇаЁ бваҐ«мЎҐ ®е®в­ЁЄ (hunter) ЇаЁ Ї®пў«Ґ­ЁЁ ЁЈа®Є  ­  «Ё­ЁЁ ®Ј­п
# 100 - ­Ґ бваҐ«пҐв, 0 - бваҐ«пҐв Є Є в®«мЄ® гўЁ¤Ёв

Crash		70
# ў­Ё¬ вҐ«м­®бвм Є Ї®¬ҐзҐ­­л¬ бвҐ­ ¬
# 100 - бЇҐжЁ «м­® ­Ґ а §ў®а зЁў Ґвбп Є ­Ё¬, 0 - а §ў®а зЁў Ґвбп ®Ўп§ вҐ«м­® Є Ў«Ё¦ ©иҐ© бвҐ­Ґ

CrashC		10
# ў­Ё¬ вҐ«м­®бвм Є Ї®¬ҐзҐ­­л¬ бвҐ­ ¬, в ­Є®ў-AI-а §агиЁвҐ«Ґ©
# 100 - бЇҐжЁ «м­® ­Ґ а §ў®а зЁў Ґвбп Є ­Ё¬, 0 - а §ў®а зЁў Ґвбп ®Ўп§ вҐ«м­® Є Ў«Ё¦ ©иҐ© бвҐ­Ґ

ItemBoomDam	50	# Ї®ўаҐ¦¤Ґ­ЁҐ ўа Ј®ў ЇаЁ ў§пвЁЁ Ў®­гб  Ў®¬Ў -Ўг« ў 	
MedicLive	65	# Є®«ЁзҐбвў® ¦Ё§­Ґ© ЇаЁЎ ў«пҐ¬ле  ЇвҐзЄ®©
RecovLive	200	# ­  бЄ®«мЄ® «ҐзЁв ®ЎмҐЄ-Ў и­п
RecovSpeed	166	# min ўаҐ¬п ¬Ґ¦¤г «ҐзҐ­ЁҐ¬ ®ЎмҐЄ-Ў и­Ё 32 = 1 бҐЄ
BigExplosion	80 	#  в®¬­л© ў§алў  - Ї®ўаҐ¦¤Ґ­ЁҐ в ­Є®ў
MineDamage	75	# Ї®ўаҐ¦¤Ґ­ЁҐ ®в ¬Ё­л


LiveFlag 0 	100	# Є®«ЁзҐбвў® ¦Ё§­Ґ© г д« Ј  (Ї « вЄ )
LiveFlag 1 	200	# бЁ­Ё© ¤®¬ЁЄ
LiveFlag 2 	300	# бҐал© ¤®¬ЁЄ

Score player 	100	# ®зЄЁ §  ў§пвЁҐ - гЎЁвЁҐ (ҐйҐ ­Ґ ­ ббзЁвлў овбп)
Score easy	2
Score normal	3
Score hard	4
Score nuc	4
Score raket	3
Score electro	3
Score bronev	3
Score boss1	100
Score boss2	200
Score boss3	600
Score electro	8
Score fire	8
Score terotgun	8

Score dzot	10
Score rotgun	10
Score recov	10
Score hostages  10
Score pillbox	10

Score bonus	10

Score bomb	10
Score shield	3
Score lopata	4
Score clock	5
Score star	6
Score medic	7	
Score zamok	9
Score ammo	10
Score airbomb	11
Score mine	13
Score bucket	14
Score defence	15
Score sc_nut	17

Score sc_key	25


rFireT easy	30	# ўаҐ¬п ЇҐаҐ§ ап¤ЄЁ ўа Ј®ў Ё ®ЎмҐЄв®ў (32 = 1 бҐЄ)
rFireT normal	40
rFireT hard	50
rFireT nuc	70
rFireT fire	5
rFireT terotgun	10
rFireT raket	50
rFireT electro	50
rFireT bronev	30
rFireT boss1	50
rFireT boss2	10
rFireT boss3	70
rFireT dzot	30
rFireT rotgun	50
rFireT recov	45

moveT player 	12	# бЄ®а®бвм ЇҐаҐ¬ҐйҐ­Ёп (§  бЄ®«мЄ® е®¤®ў ЇҐаҐбҐЄ Ґвбп Є«ҐвЄ )
moveT easy	14
moveT normal	16
moveT hard	18
moveT nuc	16
moveT raket	16
moveT electro	16
moveT bronev	32
moveT fire	20
moveT terotgun	20
moveT boss1	16
moveT boss2	26
moveT boss3	16

liveT player 	150	# Є®«ЁзҐбвў® ¦Ё§­Ґ©
liveT easy	20
liveT normal	30
liveT hard	40
liveT nuc	40
liveT raket	30
liveT electro	50
liveT terotgun	60
liveT fire	80
liveT bronev	100
liveT boss1	300
liveT boss2	500
liveT boss3	1500
liveT dzot	200
liveT rotgun	200
liveT recov	100

# бв®Ё¬®бвм Ї®ЄгЇЄЁ ў ¬ Ј §Ё­Ґ
cost_ARMOR	100	# Ѓа®­п/е_вЇ®_­в
cost_SP_M	100	# ўЁ¤Є_бвм агег
cost_SP_F	100	# ўЁ¤Є_бвм Ї®бва_«г
cost_SP_B	100	# ўЁ¤Є_бвм Ї®«м®вг Єг«_
cost_UN		100	# Њ®¦«Ёў_бвм Ї®иЄ®¤¦Ґ­­п §Ўа®х
cost_ARMOR_II	300	# Ѓа®­п/е_вЇ®_­в
cost_SP_M_II	300	# ўЁ¤Є_бвм агег
cost_SP_F_II	300	# ўЁ¤Є_бвм Ї®бва_«г
cost_SP_B_II	300	# ўЁ¤Є_бвм Ї®«м®вг Єг«_
cost_UN_II	300	# Њ®¦«Ёў_бвм Ї®иЄ®¤¦Ґ­­п §Ўа®х
cost_ARMOR_III  500	# Ѓа®­п/е_вЇ®_­в
cost_SP_M_III	500	# ўЁ¤Є_бвм агег
cost_SP_F_III	500	# ўЁ¤Є_бвм Ї®бва_«г
cost_SP_B_III	500	# ўЁ¤Є_бвм Ї®«м®вг Єг«_
cost_UN_III	500	# Њ®¦«Ёў_бвм Ї®иЄ®¤¦Ґ­­п §Ўа®х
cost_ARMOR_IIII	700	# Ѓа®­п/е_вЇ®_­в
cost_SP_M_IIII	700	# ўЁ¤Є_бвм агег
cost_SP_F_IIII	700	# ўЁ¤Є_бвм Ї®бва_«г
cost_SP_B_IIII	700	# ўЁ¤Є_бвм Ї®«м®вг Єг«_
cost_UN_IIII	700	# Њ®¦«Ёў_бвм Ї®иЄ®¤¦Ґ­­п §Ўа®х
cost_ARMOR_V    1000	# Ѓа®­п/е_вЇ®_­в


# ў«Ёп­ЁҐ ¬®¤ЁдЁЄ жЁ©, ўбҐ Ї а ¬Ґвал ў %
mod ARMOR_I	90	# г¬Ґ­миҐ­Ёп Ї®ўаҐ¦¤Ґ­Ёп 90% в.Ґ. ­  10% ¬Ґ­миҐ
mod ARMOR_II	80
mod ARMOR_III	70
mod ARMOR_IIII	60
mod ARMOR_V     1000
mod SP_M_I	105	# бЄ®а®бвм ЇҐаҐ¬ҐйҐ­Ёп ®в ­®а¬ «м­®Ј®
mod SP_M_II	110
mod SP_M_III	115
mod SP_M_IIII	120
mod SP_F_I	90	# ўаҐ¬п ЇҐаҐ§ апЄЁ, ®в ­®а¬ «м­®Ј® в.Ґ. 90%
mod SP_F_II	80
mod SP_F_III	70
mod SP_F_IIII	60
mod UN_I	120	# Ї®ўаҐ¤¦Ґ­ЁҐ ў % ®в ­®а¬ «м­®Ј®
mod UN_II	140
mod UN_III	160
mod UN_IIII	170
mod SP_B_I	115	# бЄ®а®бвм Їг«Ё
mod SP_B_II	130	 
mod SP_B_III	145	 
mod SP_B_IIII	160	  

# бв®Ё¬®бвм Ї®ЄгЇЄЁ ў ¬ Ј §Ё­Ґ
costARM GUN	100	# бв®Ё¬®бвм Ї®ЄгЇЄЁ 
costARM KULEMET	0	# бв®Ё¬®бвм Ї®ЄгЇЄЁ Їг«Ґ¬Ґв 
costARM RAKET	600	# бв®Ё¬®бвм Ї®ЄгЇЄЁ а ЄҐвл
costARM ELECTRO	700	# бв®Ё¬®бвм Ї®ЄгЇЄЁ ¬®«­ЁЁ
costARM FIRE	800	# бв®Ё¬®бвм Ї®ЄгЇЄЁ ®Ј­Ґ¬Ґв 
costARM SHOCK	500	# бв®Ё¬®бвм Ї®ЄгЇЄЁ и®ЄҐа 

# ўҐ«ЁзЁ­  Ї®Є §лў ойҐҐ ­®ў®Ґ ўаҐ¬п ЇҐаҐ§пап¤ЄЁ ў Їа®жҐ­в е ЇаЁ ў§пвЁЁ Ў®­гб®ў
# в.Ґ. §­ зҐ­ЁҐ 50 §­ зЁв г¬Ґ­миҐ­ЁҐ ўаҐ¬Ґ­Ё ЇҐаҐ§ ап¤ЄЁ ў 2 а § 
# в.Ґ. §­ зҐ­ЁҐ 33 §­ зЁв г¬Ґ­миҐ­ЁҐ ўаҐ¬Ґ­Ё ЇҐаҐ§ ап¤ЄЁ ў 3 а § 

bllrfrst1 	95	# - ЇаЁ ў§пвЁЁ ®¤­®© §ўҐ§¤л
bllrfrst2	90	# - ЇаЁ ў§пвЁЁ ¤ўге §ўҐ§¤
bllrfrst3	85	# - ЇаЁ ў§пвЁЁ ваҐе §ўҐ§¤
bllrfrbn	70	# - ЇаЁ ў§пвЁЁ Ў®­гб  Ї®ўли ойҐЈ® бЄ®а®бваҐ«м­®бвм

# а ¤Ёгб Ї®ўаҐ¦¤Ґ­Ёп в ­Є®ў ЇаЁ ў§алўҐ а ЄҐвл
randmraket 10.0 20.0 	# ЇҐаў®Ґ - ЎҐ§ ®б« Ў«Ґ­Ёп Ї®ўаҐ¦¤Ґ­Ёп ўв®а®Ґ зЁб«® б ®б« Ў«Ґ­ЁҐ¬ Ї®ўаҐ¦¤Ґ­Ёп

bullet 1 GUN
  bullspeed 22		 # - бЄ®а®бвм Ї®«Ґв  Їг«Ё min = 12 (в.Є. ­Ґ ¬®¦Ґв Ўлвм ¬Ґ­ЎиҐ бЄ®а®бвЁ в ­Є )
  bulldamage 20	   	 # - Ї®ўаҐ¦¤Ґ­Ёп (в ­Є®ў Ё ®ЎмҐЄв®ў)
  bullrefire 24		 # - ўаҐ¬п ЇҐаҐ§ ап¤ЄЁ 32 = 1 бҐЄ
  bullmaxstep 9999	                    # - а ббв®п­ЁҐ ўлбваҐ« 

# - Є ав  Ї®ўаҐ¦¤Ґ­Ёп ¤«п бвҐ­ в.Ґ. «оЎ п Їг«п ¬®¦Ґв Ї®ўаҐ¤Ёвм а §¬Ґа бвҐ­л 5е5 Є«Ґв®Є
# жЁда  Ї®Є §лў Ґв ЇаЁзЁ­Ґ­­л© гйҐаЎ
  bulltdm 0 0 0 0 0 0	 
  bulltdm 1 0 0 0 0 0
  bulltdm 2 0 0 2 0 0
  bulltdm 3 0 0 0 0 0
  bulltdm 4 0 0 0 0 0

bullet 2 KULEMET		
  bullspeed 25
  bulldamage 10
  bullrefire 8
  bullmaxstep 9999

  bulltdm 0 0 0 0 0 0
  bulltdm 1 0 0 0 0 0
  bulltdm 2 0 0 1 0 0
  bulltdm 3 0 0 0 0 0
  bulltdm 4 0 0 0 0 0

bullet 3 RAKET		
  bullspeed 15
  bulldamage 32
  bullrefire 40
  bullmaxstep 9999

  bulltdm 0 0 0 1 0 0
  bulltdm 1 0 1 1 1 0
  bulltdm 2 1 1 2 1 1
  bulltdm 3 0 1 1 1 0
  bulltdm 4 0 0 1 0 0

bullet 4 ELECTRO		
  bullspeed 25
   bulldamage 10 30
  bullrefire 35
  bullmaxstep 25

  bulltdm 0 0 0 0 0 0
  bulltdm 1 0 0 2 0 0
  bulltdm 2 0 2 4 2 0
  bulltdm 3 0 0 2 0 0
  bulltdm 4 0 0 0 0 0

bullet 5 FIRE			
  bullspeed 12
  bulldamage 15
  bullrefire 4
  bullmaxstep 10

  bulltdm 0 0 0 0 0 0
  bulltdm 1 0 0 1 0 0
  bulltdm 2 0 1 1 1 0
  bulltdm 3 0 0 1 0 0
  bulltdm 4 0 0 0 0 0

bullet 6 SHOCK		
  bullspeed 25
  bulldamage 35
  bullrefire 15
  bullmaxstep 9999

  bulltdm 0 0 0 0 0 0
  bulltdm 1 0 0 1 0 0
  bulltdm 2 0 1 1 1 0
  bulltdm 3 0 0 1 0 0
  bulltdm 4 0 0 0 0 0

bullet 7 SHOCK_S		
  bullspeed 20
  bulldamage 30
  bullrefire 17
  bullmaxstep 9999

  bulltdm 0 0 0 0 0 0
  bulltdm 1 0 0 0 0 0
  bulltdm 2 0 0 1 0 0
  bulltdm 3 0 0 0 0 0
  bulltdm 4 0 0 0 0 0

